spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 10

  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: when_missing
        timeout: 10m
      chat:
        model: llama3.2

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      indent_output: true

server:
  port: ${PORT}

cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: "GET,POST,PUT,DELETE"
  allowed-headers: "*"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.nimbusds: DEBUG
    com.rbouaro: DEBUG

extension:
  youtube:
    api-key: ${YOUTUBE_API_KEY}
    base-url: ${YOUTUBE_API_BASE_URL}

jwt:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration: ${JWT_EXPIRATION:60} # 60 minutes
  rsa:
    private-key: |
      ${PRIVATE_KEY}
    public-key: |
      ${PUBLIC_KEY}

springdoc:
  swagger-ui:
    enabled: true

openapi:
  url: ${OPENAPI_SERVER_URL}