CREATE TABLE milestones
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    roadmap_id   BIGINT                                  NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    description  TEXT,
    order_index  INTEGER                                 NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    status       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_milestones PRIMARY KEY (id)
);

CREATE TABLE resources
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    milestone_id BIGINT                                  NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    description  TEXT,
    url          VARCHAR(255)                            NOT NULL,
    type         VARCHAR(255)                            NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    status       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_resources PRIMARY KEY (id)
);

CREATE TABLE roadmaps
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_goal_id BIGINT                                  NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    description  TEXT,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_roadmaps PRIMARY KEY (id)
);

CREATE TABLE user_goals
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description TEXT,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    status      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user_goals PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    role    SMALLINT
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE roadmaps
    ADD CONSTRAINT uc_roadmaps_user_goal UNIQUE (user_goal_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE milestones
    ADD CONSTRAINT FK_MILESTONES_ON_ROADMAP FOREIGN KEY (roadmap_id) REFERENCES roadmaps (id);

ALTER TABLE resources
    ADD CONSTRAINT FK_RESOURCES_ON_MILESTONE FOREIGN KEY (milestone_id) REFERENCES milestones (id);

ALTER TABLE roadmaps
    ADD CONSTRAINT FK_ROADMAPS_ON_USER_GOAL FOREIGN KEY (user_goal_id) REFERENCES user_goals (id);

ALTER TABLE user_goals
    ADD CONSTRAINT FK_USER_GOALS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_user FOREIGN KEY (user_id) REFERENCES users (id);