CREATE TABLE milestones
(
    pk           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id           UUID                                    NOT NULL,
    roadmap_pk   BIGINT                                  NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    description  TEXT,
    order_index  INTEGER                                 NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    status       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_milestones PRIMARY KEY (pk)
);

CREATE TABLE resources
(
    pk           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id           UUID                                    NOT NULL,
    milestone_pk BIGINT                                  NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    description  TEXT,
    url          VARCHAR(255)                            NOT NULL,
    type         VARCHAR(255)                            NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    status       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_resources PRIMARY KEY (pk)
);

CREATE TABLE roadmaps
(
    pk           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id           UUID                                    NOT NULL,
    user_goal_pk BIGINT                                  NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    description  TEXT,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_roadmaps PRIMARY KEY (pk)
);

CREATE TABLE user_goals
(
    pk          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id          UUID                                    NOT NULL,
    user_pk     BIGINT                                  NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description TEXT,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    status      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user_goals PRIMARY KEY (pk)
);

CREATE TABLE user_roles
(
    user_pk BIGINT NOT NULL,
    role    SMALLINT
);

CREATE TABLE users
(
    pk               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id               UUID                                    NOT NULL,
    username         VARCHAR(255)                            NOT NULL,
    email            VARCHAR(255)                            NOT NULL,
    password         VARCHAR(255)                            NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (pk)
);

ALTER TABLE milestones
    ADD CONSTRAINT uc_milestones_id UNIQUE (id);

ALTER TABLE resources
    ADD CONSTRAINT uc_resources_id UNIQUE (id);

ALTER TABLE roadmaps
    ADD CONSTRAINT uc_roadmaps_id UNIQUE (id);

ALTER TABLE roadmaps
    ADD CONSTRAINT uc_roadmaps_user_goal_pk UNIQUE (user_goal_pk);

ALTER TABLE user_goals
    ADD CONSTRAINT uc_user_goals_id UNIQUE (id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_id UNIQUE (id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE milestones
    ADD CONSTRAINT FK_MILESTONES_ON_ROADMAP_PK FOREIGN KEY (roadmap_pk) REFERENCES roadmaps (pk);

ALTER TABLE resources
    ADD CONSTRAINT FK_RESOURCES_ON_MILESTONE_PK FOREIGN KEY (milestone_pk) REFERENCES milestones (pk);

ALTER TABLE roadmaps
    ADD CONSTRAINT FK_ROADMAPS_ON_USER_GOAL_PK FOREIGN KEY (user_goal_pk) REFERENCES user_goals (pk);

ALTER TABLE user_goals
    ADD CONSTRAINT FK_USER_GOALS_ON_USER_PK FOREIGN KEY (user_pk) REFERENCES users (pk);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_user FOREIGN KEY (user_pk) REFERENCES users (pk);