CREATE TABLE emails
(
    pk            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    recipient     VARCHAR(255)                            NOT NULL,
    template_name VARCHAR(255)                            NOT NULL,
    status        VARCHAR(255),
    retry_count   INTEGER                                 NOT NULL,
    error_message VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_emails PRIMARY KEY (pk)
);
