CREATE TABLE quizzes
(
    pk             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id             UUID                                    NOT NULL,
    milestone_pk   BIGINT,
    roadmap_pk     BIGINT,
    questions_json TEXT                                    NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_quizzes PRIMARY KEY (pk),
    CONSTRAINT uq_quizzes_id UNIQUE (id),
    CONSTRAINT uq_quizzes_milestone UNIQUE (milestone_pk),
    CONSTRAINT uq_quizzes_roadmap UNIQUE (roadmap_pk),
    CONSTRAINT fk_quizzes_milestone FOREIGN KEY (milestone_pk) REFERENCES milestones (pk),
    CONSTRAINT fk_quizzes_roadmap FOREIGN KEY (roadmap_pk) REFERENCES roadmaps (pk)
);